name: note_canvas_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  collection: ^1.17.0
  flutter_bloc: ^8.0.0
  flutter_markdown: ^0.6.0
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.0
  tabler_icons: ^2.5.0+1
  uuid: ^3.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.0
  freezed: ^2.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
